project:
  type: website
  output-dir: docs
website:
  title: "Xindi Shan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: analysis.qmd
        text: Example Analysis
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

